server {
    listen 80;
    server_name api.lugh.site;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.lugh.site;

    ssl_certificate /etc/letsencrypt/live/api.lugh.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.lugh.site/privkey.pem;

    location / {
        proxy_pass http://localhost:5050;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}